bugfix: 修复某些不规范的 CRD 声明会导致 LazyDiscoverer 频繁进行磁盘写操作的问题
TencentBlueKing/blueking-paas pull request #28
Opened 2022-11-21 07:59 UTC by shabbywu

2022-11-21 09:13 UTC, shabbywu commented on workloads/paas_wl/paas_wl/resources/base/kube_client.py
> +                    if resourcePart.resources:
其实只改了这里. 其他都是原来的代码.

2022-11-21 10:40 UTC, piglei commented on workloads/paas_wl/paas_wl/resources/base/kube_client.py
> +                    if resourcePart.resources:
建议在注释增加原代码 GitHub 链接，以及更详细的 Bug 描述。

2022-11-21 10:41 UTC, piglei requested changes
Comment required.

2022-11-21 11:55 UTC, jamesgetx commented on workloads/paas_wl/paas_wl/resources/base/kube_client.py
> +    def search(self, **kwargs):
BCS里面采用了这样的写法去完成私有方法的override，不一定推荐，但是可以少重复写一遍search
```
class XXXLazyDiscoverer(LazyDiscoverer):

    def _LazyDiscoverer__search(self,  parts, resources, reqParams)  
        ...

```

2022-11-22 02:18 UTC, shabbywu commented on workloads/paas_wl/paas_wl/resources/base/kube_client.py
> +    def search(self, **kwargs):
其实可以不重写 search 方法，只是我们用的 sdk 版本太旧，没有包含 schnee 提交给社区的那个 bugfix, 所以就顺手将那个 fix 也弄过来了。
现在这个类是保证类名一致来实现 override 私有方法，个人感觉比 _LazyDiscoverer__search 写起来好看一丢丢

2022-11-22 03:25 UTC, shabbywu commented on workloads/paas_wl/paas_wl/resources/base/kube_client.py
> +                    if resourcePart.resources:
补充了些注释

2022-11-22 08:43 UTC, piglei approved these changes

2022-11-22 08:46 UTC, merged