feat: query alert events from bkmonitor
TencentBlueKing/blueking-paas pull request #38
Opened 2022-11-24 02:10 UTC by jamesgetx

2022-11-24 03:34 UTC, shabbywu requested changes

2022-11-24 03:34 UTC, shabbywu commented on apiserver/paasng/paasng/monitoring/monitor/client.py
> +        super().__init__(stage=settings.APIGW_ENVIRONMENT, endpoint=settings.BK_API_URL_TMPL)
这些参数由调用方传递，不要在类里处理

2022-11-24 03:34 UTC, shabbywu commented on apiserver/paasng/paasng/monitoring/monitor/views.py
> +        query_params = serializer.validated_data
Nit: query_params 这个名词和 drf 的 query_params 一样，有歧义(query_params 特指 url 中的 query 参数).

2022-11-24 03:34 UTC, shabbywu commented on apiserver/paasng/paasng/monitoring/monitor/serializers.py
> +    environment = serializers.ChoiceField(choices=('stag', 'prod'), required=False)
```python
from paasng.engine.constants import AppEnvName
AppEnvName.get_choices()
```

2022-11-24 03:34 UTC, shabbywu commented on apiserver/paasng/paasng/monitoring/monitor/serializers.py
> +            f"bizId={settings.MONITOR_AS_CODE_CONF.get('bk_biz_id')}/#/event-center/detail/{data['id']}"
f-string 不宜写太复杂
```
biz_id = settings.MONITOR_AS_CODE_CONF.get('bk_biz_id')  # 拿不到值怎么办？
f"{settings.BK_MONITORV3_URL}/?"bizId={biz_id}/#/event-center/detail/{data['id']}"
```

2022-11-24 03:34 UTC, shabbywu commented on apiserver/paasng/paasng/settings/__init__.py
> +APIGW_ENVIRONMENT = settings.get('APIGW_ENVIRONMENT', 'prod')
@jiayuan929 其实我也很疑惑为什么有这么多个相似的变量

2022-11-24 03:34 UTC, shabbywu commented on apiserver/paasng/paasng/utils/datetime.py
> +    return datetime.datetime.fromtimestamp(timestamp).strftime(fmt)
为什么不能用 isoformat

```python
datetime.datetime.now().isoformat(sep=' ', timespec='seconds')
>>> '2022-11-24 11:23:25'
```

2022-11-24 03:34 UTC, shabbywu commented on apiserver/paasng/paasng/monitoring/monitor/serializers.py
> +    start_time = serializers.IntegerField(help_text='告警开始时间', source='begin_time')
这里太隐晦了，给到前端的 `start_time` 和 `end_time` 实际上是 string 类型。
建议:
1. 在 QueryAlerts.query 里加多一层返回值的抽象。或者干脆直接返回时间戳吧。在前端里处理也不是不可以。
2. start_time, end_time 定义成 SerializerMethodField

不要搞这么隐晦的写法，如果不是我翻了 convert_timestamp_to_str 的调用地方都没发现这个类型不一致

2022-11-24 08:37 UTC, jamesgetx commented on apiserver/paasng/paasng/monitoring/monitor/serializers.py
> +    start_time = serializers.IntegerField(help_text='告警开始时间', source='begin_time')
这段逻辑在你review之后已经做了调整(因为自己review的时候发现比较隐患)，可以看下修改后的https://github.com/TencentBlueKing/blueking-paas/pull/38/files#diff-a7a8a48787e590f5b17ee1290dc56c5f2fb7a6b4da76ba2cdbadf56c3095044a)

2022-11-28 15:54 UTC, jamesgetx commented on apiserver/paasng/paasng/monitoring/monitor/alert.py
> +        return query_string
接口中有个 conditions，看文档描述只支持eq和neq，没有模糊匹配

2022-11-29 08:15 UTC, piglei commented on apiserver/paasng/paasng/monitoring/monitor/serializers.py
> +            raise serializers.ValidationError("end_time must occur after start_time")
Nit："end_time must be greater than start_time"

2022-11-29 08:15 UTC, piglei commented on apiserver/paasng/paasng/monitoring/monitor/serializers.py
> +    def get_detail_link(self, instance) -> str:
这个方法为什么要放在序列器里呢？感觉挺独立的，和序列器好像没什么关系。

2022-11-29 08:15 UTC, piglei commented on apiserver/paasng/paasng/settings/__init__.py
> +APIGW_ENVIRONMENT = settings.get('APIGW_ENVIRONMENT', 'prod')
如果暂时不统一的话，建议把名字的格式改成一致，比如都用 `_STAGE` 结尾。

2022-11-29 08:15 UTC, piglei commented on apiserver/paasng/paasng/utils/datetime.py
> +    return datetime.datetime.fromtimestamp(timestamp).strftime(fmt)
这个 timespec 有点厉害

2022-11-30 02:07 UTC, jamesgetx commented on apiserver/paasng/paasng/monitoring/monitor/serializers.py
> +    def get_detail_link(self, instance) -> str:
这个序列器主要用于序列化，其中有detail_link字段，`get_detail_link`是获取的方法

2022-12-07 07:42 UTC, jamesgetx commented on apiserver/paasng/paasng/monitoring/monitor/alert.py
> +class QueryAlerts:
已调整

2022-12-07 10:23 UTC, jamesgetx commented on apiserver/paasng/paasng/settings/__init__.py
> +APIGW_ENVIRONMENT = settings.get('APIGW_ENVIRONMENT', 'prod')
讨论后，再起一个 pr 统一调整

2022-12-09 08:23 UTC, shabbywu approved these changes

2022-12-09 08:34 UTC, merged