feat: 国际化翻译 mr
TencentBlueKing/blueking-paas pull request #520
Opened 2023-06-26 06:55 UTC by jiayuan929

2023-06-26 06:58 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  联系BK助手: 'Contact BK Assistant',
这里有问题，我一会再来给正确的

2023-06-26 07:28 UTC, HeraZhang requested changes

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  '蓝鲸PaaS平台 v3 版本分配的独立域名，如：': 'The independent domain name assigned by the v3 version of the BlueKing PaaS platform, such as:',
The independent domain name assigned by the v3 version of the BlueKing PaaS, such as:

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  '蓝鲸PaaS平台分配的子路径访问地址，如：': 'Sub-path access addresses allocated by the BlueWhale PaaS platform, such as:',
Sub-path access addresses allocated by the BlueKing PaaS, such as:

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  在蓝鲸PaaS平台上注册过的独立域名: 'An independent domain name registered on the BlueKing PaaS platform',
An independent domain name registered on the BlueKing PaaS

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  蓝鲸插件: 'bk-plugin',
专有名词？ BK plugin ？

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  '确认停止【构建阶段】吗？': 'Are you sure to stop【Build Phase】?',
Are you sure to stop "Build Phase" ?

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  '确认停止【部署阶段】吗？': 'Are you sure you want to stop the【Deployment Phase】?',
Are you sure you want to stop the "Deployment Phase" ?

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  '应用市场 (移动端)': 'APP Market (Mobile)',
APP Market  要是作为功能的话， Market 跟 APP 在一起，统一用 APP Market ，不是 APP market

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  容器端口: 'container port',
Container port

上下文推测，好像要大写

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  '2. 当你确认一切功能正常运行后，便可以点击【确认迁移】按钮来完成迁移。': '2. After you confirm that all functions are running normally, you can click the [Confirm Migration] button to complete the migration.',
2. After you confirm that all functions are running normally, you can click the "Confirm Migration" button to complete the migration.

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  '在当前迁移流程完成前 [执行迁移-部署新应用-访问新应用-测试验证-确认迁移]，你将无法开始新的迁移工作。': 'You will not be able to start a new migration until the current migration process is complete [Perform Migration - Deploy New APP - Access
You will not be able to start a new migration until the current migration process is complete "Perform Migration - Deploy New APP - Access New APP - Test Verification - Confirm Migration".

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  '点击【开启迁移】后，你的应用服务将不会受到任何影响': 'Your APP services will not be affected in any way after clicking [Enable Migration]',
Your APP services will not be affected in any way after clicking "Enable Migration"

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  '帮助文档：': 'Help documentation: ',
Documentation:

一个单词就够了

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  '来自标准运维 v3': 'from bksops',
from BKSops

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  '帮助文档 ：': 'Help documentation: ',
Documentation:

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  快速开始: 'quick start',
Quick start

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  数据视图: 'data view',
Data view

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  '蓝鲸智云可视化开发平台提供了前端页面在线可视化拖拽组装、配置编辑、源码生成、二次开发等能力。旨在帮助用户通过尽量少的手写代码的方式快速设计和开发 SaaS': 'The BlueKing Lesscode provides online visual assembly of front-end pages, configuration editing, source code genera
LessCode

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  '蓝鲸官方应用市场提供“推荐应用”广告位，帮助您更好的宣传应用': 'The official APP market of BlueKing provides "Recommended APP" advertising space to help you better promote the APP',
APP Market

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  '是否停用【': 'Whether to disable【',
Whether to disable "

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  '】移动端配置': '】Mobile end configuration',
" Mobile end configuration

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  '开始前，请确认应用【': 'Before starting, please confirm the APP【',
Before starting, please confirm the APP "

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  '】，我们将单独处理您的迁移请求。': '】, we will handle your migration request separately.',
" , we will handle your migration request separately.

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  '应用 [': 'APP [',
APP "

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  '] 正在进行': '] ',
"

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  社区: 'Community',
一会看看nek还要修订不

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  技术支持: 'Technical Support',
Support

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  社区论坛: 'Community',
Forum

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  产品官网: 'Official Website',
Official

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  社区: 'Community',
Forum

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  文档: 'Documents',
Documentation

2023-06-26 07:28 UTC, HeraZhang commented on webfe/package_vue/src/language/lang/en.js
> -  蓝鲸论坛: 'BlueKing Forum',
Forum

2023-06-26 07:39 UTC, jiayuan929 commented on webfe/package_vue/src/language/lang/en.js
> -  '是否停用【': 'Whether to disable【',
这个是需要根据上下午语境带上的

2023-06-26 07:39 UTC, jiayuan929 commented on webfe/package_vue/src/language/lang/en.js
> -  '】移动端配置': '】Mobile end configuration',
这个是需要根据上下午语境带上的

2023-06-26 07:40 UTC, jiayuan929 commented on webfe/package_vue/src/language/lang/en.js
> -  '开始前，请确认应用【': 'Before starting, please confirm the APP【',
这个是需要根据上下午语境带上的

2023-06-26 12:20 UTC, huangpeng0428 commented on webfe/package_vue/src/language/lang/en.js
> -  联系BK助手: 'Contact BK Assistant',
Contact BK Customer Service

2023-06-27 03:44 UTC, leafage-collb commented on webfe/package_vue/src/language/lang/en.js
> -  联系BK助手: 'Contact BK Assistant',
已修复

2023-06-27 03:45 UTC, leafage-collb commented on webfe/package_vue/src/language/lang/en.js
> -  蓝鲸桌面: 'BlueKing desktop',
已修改

2023-06-27 03:45 UTC, leafage-collb commented on webfe/package_vue/src/language/lang/en.js
> -  '蓝鲸PaaS平台 v3 版本分配的独立域名，如：': 'The independent domain name assigned by the v3 version of the BlueKing PaaS platform, such as:',
已修改

2023-06-27 03:45 UTC, leafage-collb commented on webfe/package_vue/src/language/lang/en.js
> -  请选择: 'please choose',
已修改

2023-06-27 03:46 UTC, leafage-collb commented on webfe/package_vue/src/language/lang/en.js
> -  '蓝鲸PaaS平台分配的子路径访问地址，如：': 'Sub-path access addresses allocated by the BlueWhale PaaS platform, such as:',
已修改

2023-06-27 03:46 UTC, leafage-collb commented on webfe/package_vue/src/language/lang/en.js
> -  在蓝鲸PaaS平台上注册过的独立域名: 'An independent domain name registered on the BlueKing PaaS platform',
已修改

2023-06-27 03:46 UTC, leafage-collb commented on webfe/package_vue/src/language/lang/en.js
> -  社区论坛: 'Community',
已修改

2023-06-27 03:47 UTC, leafage-collb commented on webfe/package_vue/src/language/lang/en.js
> -  产品官网: 'Official Website',
已修改

2023-06-27 03:47 UTC, leafage-collb commented on webfe/package_vue/src/language/lang/en.js
> -  社区: 'Community',
已修改

2023-06-27 03:47 UTC, leafage-collb commented on webfe/package_vue/src/language/lang/en.js
> -  文档: 'Documents',
已修改

2023-06-27 03:47 UTC, leafage-collb commented on webfe/package_vue/src/language/lang/en.js
> -  蓝鲸论坛: 'BlueKing Forum',
已修改

2023-06-27 06:52 UTC, closed without merging